### ISSUE TITLE
AttributeError: 'API' 

### ISSUE THREAD

**Issue by pirica** [FortniteFevers/Fortnite-Shop-Bot#1]
IMAGE GENERATING COMPLETE - Generated image in 76.93 seconds!

Compressed image!

```
Traceback (most recent call last):
  File "H:\Fortnite-Shop-Bot-main\bot.py", line 393, in genshop
    api.update_with_media(f'shop.jpg', text)
    ^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'API' object has no attribute 'update_with_media'. Did you mean: 'update_status_with_media'?

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "H:\Fortnite-Shop-Bot-main\bot.py", line 455, in <module>
    genshop()
  File "H:\Fortnite-Shop-Bot-main\bot.py", line 396, in genshop
    api.update_with_media(f'shop.jpg', text)
    ^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'API' object has no attribute 'update_with_media'. Did you mean: 'update_status_with_media'?
```

Please help...

**Comment by FortniteFevers** [comment]
Just replace the line of code "api.update_with_media" with "update_status_with_media"

This has to do with your version of Tweepy
